### ISSUE TITLE
Windows Bitcoin icon needs to be replaced by Veil icon

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#35]
https://imgur.com/f2lBTrI

1. Windows Bitcoin icon needs to be replaced by Veil icon

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by ianGre** [comment]
I don't see any Bitcoin icon (in the second Windows x64 release) testnet-2
 d5cbc6b. I presume this has been fixed. Icons are Veil's now.

**Comment by VeilDango** [comment]
Reopen.

Issue still here as of testnet-5. Bitcoin icon on my taskbar and upper left window menu.

Bitcoin splash on installation screen.

**Comment by ianGre** [comment]
Veil icons, not Bitcoin, are in Start menu, the program (top-left corner) and in the Taskbar in
Veil Core version v0.0.9.9-b767ef64c (64-bit) Windows 10. I cannot comment on the installation splash screen, except that I don't remember seeing it when I installed earlier today. There's another new binary, so I'll install that one shortly. 

** COULD this be some kind of icon caching problem? ** I never had a Windows version with a Bitcoin logo on this VM.

**Comment by VeilDango** [comment]
Bitcoin icon replaced for taskbar and upper left window menu.

Bitcoin installation image still there in testnet-7.

**Comment by ianGre** [comment]
![screen shot 2018-12-30 at 12 09 30 pm](https://user-images.githubusercontent.com/36124423/50544023-6d219800-0c3c-11e9-90ba-f016166eebf3.png)
![screen shot 2018-12-30 at 12 09 07 pm](https://user-images.githubusercontent.com/36124423/50544024-6d219800-0c3c-11e9-8db2-5b42bcd5e360.png)
![screen shot 2018-12-30 at 12 07 26 pm](https://user-images.githubusercontent.com/36124423/50544025-6dba2e80-0c3c-11e9-9b87-c64838d6e82a.png)
Here are three Bitcoin logos or references in the Windows installation from the build release a couple of hours ago.

**Comment by 4x13** [comment]
Should be fixed

**Comment by StrontiumZ38** [comment]
This can be closed.

**Comment by VeilDango** [comment]
![image](https://i.imgur.com/EV2M5M7.png)
![image2](https://i.imgur.com/9BxPmbP.png)
The logo is quite blurry.

**Comment by ianGre** [comment]
It does look a bit rough, but I can live with that. By the time they get _using_ the wallet they will forget about blurry graphics during installation.

**Comment by 4x13** [comment]
fixed
