### ISSUE TITLE
Veil wallet 1.3 wont completely sync.

### ISSUE THREAD

**Issue by mreash16** [Veil-Project/veil#593]
After about 3-4 hours of syncing or rescaning the block chain, the wallet just closes. No error message or anything. The wallet just closes, it happens everytime when the wallet is 62% of the blockchain rescan is complete. So I can't scan the last 75000 block of the block chain

**Comment by 4x13** [comment]
The issue has been fixed already, please build from the master branch. An official update will be released soon.

**Comment by Strunczez** [comment]
Are you serious? Please build? You want to grow this coin or what? You have to AIM it to all people, not only those who have compilers and know how to compile!
Wallet still cannot be synced. Hangs like s**t.
FIX IT ASAP and PUBLISH!

**Comment by presstab** [comment]
This particular issue is fixed. A new release will be coming out soon that has prebuilt binaries for everyone.
