### ISSUE TITLE
Marked text disappears visually on dropdown menus

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#60]
If you mark text inside the wallet (for example a typed in adress) it visually disappears (guess it has the same color as the background)

Reproduce:
Type in an Adress in the Sender field and press ctrl+a

@veildev

**Comment by MisterKangaroo** [comment]
![marked adress](https://user-images.githubusercontent.com/43561981/50498987-bf4c9880-0a45-11e9-9782-f9cafe8e9e3b.PNG)

**Comment by veildev** [comment]
done on #59

**Comment by MisterKangaroo** [comment]
Still happens in the Advanced options "Peers" section if mouseover on "ban for x hours..."

**Comment by StrontiumZ38** [comment]
![image](https://user-images.githubusercontent.com/38264865/50580592-9c7e1200-0e93-11e9-9892-275b7a6ec545.png)
When highlighted it looks like this for me.
Drop down options do have this problem still though.

**Comment by ianGre** [comment]
A have noticed this problem on dropdown items too. Not only in this software, but it is annoying when it happens.

**Comment by veildev** [comment]
done.

**Comment by Larcea** [comment]
I have this issue with 1.0.0.9.

However I have pegged it to the "Dark" appearance for the MacOS Theme.

When I switch to "Light" the text all comes back.

Dark Theme:
![screen shot 2019-01-11 at 3 47 23 pm](https://user-images.githubusercontent.com/38234120/51061819-29bf1600-15ba-11e9-9689-171a003376d1.png)

Light Theme:
![screen shot 2019-01-11 at 3 52 03 pm](https://user-images.githubusercontent.com/38234120/51061840-3ba0b900-15ba-11e9-921c-12357dd890f9.png)
